sudo: required
services:
  - docker

before_install:
  - docker build -t prathamesh99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run prathamesh99/react-test npm run test -- --coverage

after_success:
  - docker build -t prathamesh99/multi-client ./client
  - docker build -t prathamesh99/multi-nginx ./nginx
  - docker build -t prathamesh99/multi-server ./server
  - docker build -t prathamesh99/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images
  - docker push prathamesh99/multi-nginx
  - docker push prathamesh99/multi-client
  - docker push prathamesh99/multi-server
  - docker push prathamesh99/multi-worker

